waterfox: G5.1.3 update

diff --git a/waterfox/PKGBUILD b/waterfox/PKGBUILD
--- a/waterfox/PKGBUILD
+++ b/waterfox/PKGBUILD
@@ -3,7 +3,7 @@
 # Source repo: https://github.com/WaterfoxCo/Waterfox
 
 pkgname=waterfox
-pkgver=G5.1.1
+pkgver=G5.1.3
 _archivename=$pkgver
 
 pkgrel=1
@@ -25,7 +25,7 @@ options=(!emptydirs !makeflags !strip !lto !debug)
 source=(
 	Waterfox-$_archivename.tar.gz::https://github.com/WaterfoxCo/Waterfox/archive/$_archivename.tar.gz
 	$pkgname.desktop )
-sha256sums=( ab5a5359f3416119ec46bc122c7c58d2ae3fc62cf3e162231a21ba7f65882e9e SKIP )
+sha256sums=( 459cf149a93a1707ed60298f65d6121ede160e01a17b680ebfd9d3ff2257d507 SKIP )
 # _disable_pgo=y # uncomment this to disable building the profiled browser and using PGO
 
 local_patches=()
@@ -63,6 +63,7 @@ ac_add_options --disable-updater
 ac_add_options --enable-application=browser
 ac_add_options --enable-install-strip
 ac_add_options --enable-strip
+ac_add_options --enable-jxl
 ac_add_options --disable-bootstrap
 ac_add_options --disable-tests
 
@@ -92,7 +93,8 @@ END
 	local p
 	for p in ${local_patches[@]}; do
 		echo "--- applying local patch: $p"
-		patch --dry-run -tNp1 -i "$srcdir"/$p && patch -tNp1 -i "$srcdir"/$p
+		patch --dry-run -tNp1 -i "$srcdir"/$p && patch -tNp1 -i "$srcdir"/$p \
+			|| { echo >&2 "ERROR: patch failed - $p"; exit 1; }
 	done
 }
 
